[package]
name = "ouro-hiss"
version.workspace = true
edition.workspace = true

[dependencies]
ouro-cluster = { path = "../cluster" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
libc.workspace = true
tokio = { version = "1", features = ["full"] }
rustyline = "18.0.1"

[lib]
name = "ouro_hiss"
path = "src/lib.rs"

[dev-dependencies]
bitnet-rs = { path = "../bitnet-rs" }
serde_json.workspace = true

[[bin]]
name = "ouro-hiss"
path = "src/main.rs"

[[bin]]
name = "ouro-ttyd"
path = "src/bin/ouro-ttyd.rs"

[[bin]]
name = "ouro-registry"
path = "src/bin/ouro-registry.rs"
